# Site settings
title: Convertify Blog
email: cooperm@susteen.com
description: > # this means to ignore newlines until "baseurl:"
  All things CRO.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.convertify.io" # the base hostname & protocol for your site
twitter_username: convertify
github_username:  convertify

# Build settings
markdown: kramdown
